# Generated by Django 2.2.4 on 2019-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='practice-blog'),
            preserve_default=False,
        ),
    ]
