# Generated by Django 2.2.4 on 2019-08-06 15:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_auto_20190806_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
