# Generated by Django 2.2.4 on 2019-08-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('git_link', models.URLField()),
                ('image', models.FileField(null=True, upload_to='projects')),
            ],
            options={
                'ordering': ['name', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('first_name', models.CharField(max_length=44)),
                ('last_name', models.CharField(max_length=44)),
                ('personal_bio', models.TextField()),
                ('professional_bio', models.TextField()),
                ('avatar', models.FileField(upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
